# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: build and execute lpp test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up lpp environment
        run: |
          curl -fsSL https://get.docker.com | bash
          sudo usermod -aG docker $USER
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install git+https://github.com/f0reachARR/lpp_test.git --force

      - name: execute lpp test
        working-directory: ${{github.workspace}}/1/
        run: lpptest 01test
