# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdir: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/${{ matrix.subdir }}/build -S ${{ github.workspace }}/${{ matrix.subdir }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/${{ matrix.subdir }}/build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ github.workspace }}/${{ matrix.subdir }}/build
        run: ctest -C ${{ env.BUILD_TYPE }}
